import { IntegrationPlatform } from '@prisma/client';

export type IntegrationCategory =
  | 'PPC'
  | 'SEO'
  | 'SOCIAL'
  | 'EMAIL'
  | 'ECOMMERCE'
  | 'ANALYTICS'
  | 'CALL_TRACKING'
  | 'LOCAL'
  | 'DATABASE';

export type AuthType = 'OAUTH' | 'API_KEY' | 'BOTH';

export interface PlatformMeta {
  key: IntegrationPlatform;
  name: string;
  /** Primary category — used for filtering */
  category: IntegrationCategory;
  /** Secondary categories this platform also belongs to (shows in multiple filter tabs) */
  altCategories?: IntegrationCategory[];
  authType: AuthType;
  description: string;
  /** true = OAuth/API endpoints are built and accepting credentials */
  isImplemented: boolean;
  /** Short tag shown in UI, e.g. "Google OAuth", "API Key" */
  authLabel: string;
}

export const PLATFORM_CATALOG: PlatformMeta[] = [
  // ─── Already implemented ──────────────────────────────────────────────────
  {
    key: IntegrationPlatform.GA4,
    name: 'Google Analytics 4',
    category: 'ANALYTICS',
    authType: 'OAUTH',
    authLabel: 'Google OAuth',
    description: 'Track website traffic, user behaviour, conversions, and events from Google Analytics 4.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.GOOGLE_ADS,
    name: 'Google Ads',
    category: 'PPC',
    authType: 'OAUTH',
    authLabel: 'Google OAuth',
    description: 'Pull campaign performance, clicks, impressions, spend, and conversions from Google Ads.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.META_ADS,
    name: 'Meta Ads',
    category: 'PPC',
    altCategories: ['SOCIAL'],
    authType: 'OAUTH',
    authLabel: 'Facebook OAuth',
    description: 'Sync Facebook and Instagram ad campaign data — spend, reach, clicks, and conversions.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.GOOGLE_SEARCH_CONSOLE,
    name: 'Google Search Console',
    category: 'SEO',
    authType: 'OAUTH',
    authLabel: 'Google OAuth',
    description: 'Monitor organic search impressions, clicks, average position, and keyword rankings.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.LINKEDIN_ADS,
    name: 'LinkedIn Ads',
    category: 'PPC',
    authType: 'OAUTH',
    authLabel: 'LinkedIn OAuth',
    description: 'Track B2B ad performance — impressions, clicks, spend, and lead gen form submissions.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.YOUTUBE_ANALYTICS,
    name: 'YouTube',
    category: 'SOCIAL',
    authType: 'OAUTH',
    authLabel: 'Google OAuth',
    description: 'Monitor video views, watch time, subscribers, and channel engagement metrics.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.TIKTOK_ADS,
    name: 'TikTok Ads',
    category: 'PPC',
    altCategories: ['SOCIAL'],
    authType: 'OAUTH',
    authLabel: 'TikTok OAuth',
    description: 'Pull TikTok paid campaign metrics — impressions, clicks, spend, and video views.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.AMAZON_ADS,
    name: 'Amazon Ads',
    category: 'PPC',
    authType: 'OAUTH',
    authLabel: 'Amazon OAuth',
    description: 'Sync Amazon Advertising campaign data — Sponsored Products, Brands, and Display.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.MAILCHIMP,
    name: 'Mailchimp',
    category: 'EMAIL',
    authType: 'OAUTH',
    authLabel: 'Mailchimp OAuth',
    description: 'Track email campaign opens, clicks, unsubscribes, and list growth over time.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.SHOPIFY,
    name: 'Shopify',
    category: 'ECOMMERCE',
    authType: 'OAUTH',
    authLabel: 'Shopify OAuth',
    description: 'Pull revenue, orders, average order value, and product sales from Shopify stores.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.SEMRUSH,
    name: 'Semrush',
    category: 'SEO',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Import keyword rankings, organic traffic estimates, backlinks, and site audit data.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.MICROSOFT_ADS,
    name: 'Microsoft Ads',
    category: 'PPC',
    authType: 'OAUTH',
    authLabel: 'Microsoft OAuth',
    description: 'Sync Bing / Microsoft Ads campaign performance — clicks, impressions, spend, and conversions.',
    isImplemented: true,
  },

  // ─── PPC ──────────────────────────────────────────────────────────────────
  {
    key: IntegrationPlatform.PINTEREST_ADS,
    name: 'Pinterest Ads',
    category: 'PPC',
    authType: 'OAUTH',
    authLabel: 'Pinterest OAuth',
    description: 'Track Pinterest paid campaign metrics — impressions, saves, clicks, and spend.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.SNAPCHAT_ADS,
    name: 'Snapchat Ads',
    category: 'PPC',
    authType: 'OAUTH',
    authLabel: 'Snapchat OAuth',
    description: 'Pull Snapchat Ads performance data — impressions, swipe-ups, spend, and story views.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.X_ADS,
    name: 'X Ads',
    category: 'PPC',
    altCategories: ['SOCIAL'],
    authType: 'OAUTH',
    authLabel: 'X OAuth',
    description: 'Sync X (Twitter) paid campaign data — impressions, engagements, clicks, and spend.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.REDDIT_ADS,
    name: 'Reddit Ads',
    category: 'PPC',
    authType: 'OAUTH',
    authLabel: 'Reddit OAuth',
    description: 'Monitor Reddit Ads campaign performance — clicks, impressions, spend, and conversions.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.ADROLL,
    name: 'AdRoll',
    category: 'PPC',
    authType: 'OAUTH',
    authLabel: 'OAuth',
    description: 'Pull retargeting and prospecting campaign metrics from AdRoll.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.GOOGLE_AD_MANAGER,
    name: 'Google Ad Manager',
    category: 'PPC',
    authType: 'OAUTH',
    authLabel: 'Google OAuth',
    description: 'Sync programmatic ad delivery data — impressions, CTR, revenue, and fill rates.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.GOOGLE_DV360,
    name: 'Google Display & Video 360',
    category: 'PPC',
    authType: 'OAUTH',
    authLabel: 'Google OAuth',
    description: 'Pull Display & Video 360 programmatic campaign data — reach, frequency, spend, and conversions.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.GOOGLE_LOCAL_SERVICES_ADS,
    name: 'Google Local Services Ads',
    category: 'PPC',
    altCategories: ['LOCAL'],
    authType: 'OAUTH',
    authLabel: 'Google OAuth',
    description: 'Track Local Services Ads leads, calls, and spend for service-area businesses.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.INSTAGRAM_ADS,
    name: 'Instagram Ads',
    category: 'PPC',
    altCategories: ['SOCIAL'],
    authType: 'OAUTH',
    authLabel: 'Facebook OAuth',
    description: 'Pull Instagram paid campaign data — reach, impressions, clicks, and spend via Meta API.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.SPOTIFY_ADS,
    name: 'Spotify Ads',
    category: 'PPC',
    authType: 'OAUTH',
    authLabel: 'Spotify OAuth',
    description: 'Sync Spotify Ads Studio campaign data — impressions, clicks, reach, and audio completions.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.STACKADAPT,
    name: 'StackAdapt',
    category: 'PPC',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull programmatic display, native, and video campaign data from StackAdapt.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.SIMPLIFI,
    name: 'Simpli.fi',
    category: 'PPC',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Import programmatic advertising campaign metrics from Simpli.fi DSP.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.CHOOZLE,
    name: 'Choozle',
    category: 'PPC',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Sync digital advertising campaign data from the Choozle DSP platform.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.GROUNDTRUTH,
    name: 'GroundTruth',
    category: 'PPC',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull location-based mobile advertising campaign data from GroundTruth.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.BASIS_PLATFORM,
    name: 'Basis Platform',
    category: 'PPC',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Sync programmatic, search, and social campaign data from Centro Basis.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.YELP_ADS,
    name: 'Yelp Ads',
    category: 'PPC',
    altCategories: ['LOCAL'],
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Track Yelp Ads performance — impressions, clicks, and direction requests.',
    isImplemented: true,
  },

  // ─── SEO ──────────────────────────────────────────────────────────────────
  {
    key: IntegrationPlatform.AHREFS,
    name: 'Ahrefs',
    category: 'SEO',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull backlink data, organic keyword rankings, domain rating, and traffic estimates from Ahrefs.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.MOZ,
    name: 'Moz',
    category: 'SEO',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Import Domain Authority, page authority, backlinks, and keyword rankings from Moz.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.SE_RANKING,
    name: 'SE Ranking',
    category: 'SEO',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Sync keyword positions, website audits, and backlink monitoring data from SE Ranking.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.MAJESTIC_SEO,
    name: 'Majestic SEO',
    category: 'SEO',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull Trust Flow, Citation Flow, and backlink data from Majestic SEO.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.BING_WEBMASTER_TOOLS,
    name: 'Bing Webmaster Tools',
    category: 'SEO',
    authType: 'OAUTH',
    authLabel: 'Microsoft OAuth',
    description: 'Monitor Bing organic search impressions, clicks, pages crawled, and index status.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.GOOGLE_BUSINESS_PROFILE,
    name: 'Google Business Profile',
    category: 'LOCAL',
    altCategories: ['SEO'],
    authType: 'OAUTH',
    authLabel: 'Google OAuth',
    description: 'Track Google Business Profile views, searches, direction requests, and calls.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.GOOGLE_LIGHTHOUSE,
    name: 'Google Lighthouse',
    category: 'SEO',
    authType: 'API_KEY',
    authLabel: 'No Auth',
    description: 'Run automated Lighthouse audits for performance, accessibility, SEO, and best practices.',
    isImplemented: false,
  },
  {
    key: IntegrationPlatform.GOOGLE_PAGESPEED,
    name: 'Google PageSpeed',
    category: 'SEO',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull Core Web Vitals and PageSpeed scores for desktop and mobile from Google PageSpeed Insights.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.RANK_TRACKER,
    name: 'Rank Tracker',
    category: 'SEO',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Monitor daily keyword ranking positions across Google, Bing, and Yahoo.',
    isImplemented: false,
  },
  {
    key: IntegrationPlatform.BACKLINK_MONITOR,
    name: 'Backlink Monitor',
    category: 'SEO',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Track new and lost backlinks, domain authority changes, and link health over time.',
    isImplemented: false,
  },

  // ─── Social (organic) ─────────────────────────────────────────────────────
  {
    key: IntegrationPlatform.FACEBOOK_ORGANIC,
    name: 'Facebook',
    category: 'SOCIAL',
    authType: 'OAUTH',
    authLabel: 'Facebook OAuth',
    description: 'Track organic Facebook Page metrics — reach, impressions, likes, comments, and shares.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.INSTAGRAM_ORGANIC,
    name: 'Instagram',
    category: 'SOCIAL',
    authType: 'OAUTH',
    authLabel: 'Facebook OAuth',
    description: 'Monitor organic Instagram metrics — followers, reach, impressions, and post engagement.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.PINTEREST_ORGANIC,
    name: 'Pinterest',
    category: 'SOCIAL',
    authType: 'OAUTH',
    authLabel: 'Pinterest OAuth',
    description: 'Track organic Pinterest metrics — impressions, saves, clicks, and audience data.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.VIMEO,
    name: 'Vimeo',
    category: 'SOCIAL',
    authType: 'OAUTH',
    authLabel: 'Vimeo OAuth',
    description: 'Pull video performance metrics from Vimeo — plays, finishes, likes, and comments.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.X_ORGANIC,
    name: 'X (Twitter)',
    category: 'SOCIAL',
    authType: 'OAUTH',
    authLabel: 'X OAuth',
    description: 'Track organic X (Twitter) account metrics — impressions, engagements, follows, and replies.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.TIKTOK_ORGANIC,
    name: 'TikTok',
    category: 'SOCIAL',
    authType: 'OAUTH',
    authLabel: 'TikTok OAuth',
    description: 'Monitor organic TikTok account metrics — views, likes, comments, shares, and followers.',
    isImplemented: true,
  },

  // ─── Email Marketing ──────────────────────────────────────────────────────
  {
    key: IntegrationPlatform.KLAVIYO,
    name: 'Klaviyo',
    category: 'EMAIL',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull email and SMS campaign performance from Klaviyo — opens, clicks, revenue, and list growth.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.ACTIVECAMPAIGN,
    name: 'ActiveCampaign',
    category: 'EMAIL',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Sync email campaign metrics and automation performance from ActiveCampaign.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.BREVO,
    name: 'Brevo',
    category: 'EMAIL',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Import email campaign sends, opens, clicks, and unsubscribes from Brevo (formerly Sendinblue).',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.CONSTANT_CONTACT,
    name: 'Constant Contact',
    category: 'EMAIL',
    authType: 'OAUTH',
    authLabel: 'OAuth',
    description: 'Track email campaign performance — sends, opens, clicks, and list growth from Constant Contact.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.CAMPAIGN_MONITOR,
    name: 'Campaign Monitor',
    category: 'EMAIL',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull email campaign analytics from Campaign Monitor — opens, clicks, bounces, and revenue.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.CONVERTKIT,
    name: 'ConvertKit',
    category: 'EMAIL',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Sync subscriber growth, email sequence performance, and broadcast metrics from ConvertKit.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.DRIP,
    name: 'Drip',
    category: 'EMAIL',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Import email and SMS campaign metrics from Drip — opens, clicks, revenue, and workflow performance.',
    isImplemented: true,
  },

  // ─── Ecommerce ────────────────────────────────────────────────────────────
  {
    key: IntegrationPlatform.WOOCOMMERCE,
    name: 'WooCommerce',
    category: 'ECOMMERCE',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull WooCommerce store data — revenue, orders, AOV, refunds, and top products.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.BIGCOMMERCE,
    name: 'BigCommerce',
    category: 'ECOMMERCE',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Sync BigCommerce store metrics — revenue, orders, conversion rate, and product performance.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.STRIPE_ECOMMERCE,
    name: 'Stripe',
    category: 'ECOMMERCE',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Track Stripe revenue, new customers, refunds, and MRR for subscription and ecommerce businesses.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.KEAP,
    name: 'Keap',
    category: 'ECOMMERCE',
    altCategories: ['EMAIL'],
    authType: 'OAUTH',
    authLabel: 'OAuth',
    description: 'Sync Keap (Infusionsoft) CRM and ecommerce data — contacts, revenue, and pipeline metrics.',
    isImplemented: true,
  },

  // ─── Analytics & CRM ──────────────────────────────────────────────────────
  {
    key: IntegrationPlatform.HUBSPOT,
    name: 'HubSpot',
    category: 'ANALYTICS',
    altCategories: ['EMAIL'],
    authType: 'OAUTH',
    authLabel: 'HubSpot OAuth',
    description: 'Pull HubSpot CRM data — contacts, deals, revenue, email performance, and pipeline stages.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.MATOMO,
    name: 'Matomo',
    category: 'ANALYTICS',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Import privacy-friendly web analytics from Matomo — visits, bounce rate, goals, and funnels.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.SALESFORCE,
    name: 'Salesforce',
    category: 'ANALYTICS',
    altCategories: ['EMAIL'],
    authType: 'OAUTH',
    authLabel: 'Salesforce OAuth',
    description: 'Sync Salesforce CRM pipeline metrics — leads, opportunities, revenue, and win rates.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.SHARPSPRING,
    name: 'SharpSpring',
    category: 'ANALYTICS',
    altCategories: ['EMAIL'],
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull SharpSpring marketing automation data — leads, email campaigns, and pipeline metrics.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.GRAVITY_FORMS,
    name: 'Gravity Forms',
    category: 'ANALYTICS',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Track form submissions, conversion rates, and entry data from Gravity Forms on WordPress.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.UNBOUNCE,
    name: 'Unbounce',
    category: 'ANALYTICS',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Sync landing page performance from Unbounce — visits, conversions, conversion rate, and A/B test results.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.HIGHLEVEL,
    name: 'HighLevel',
    category: 'ANALYTICS',
    altCategories: ['CALL_TRACKING'],
    authType: 'OAUTH',
    authLabel: 'OAuth',
    description: 'Pull HighLevel (GoHighLevel) CRM and marketing automation data — leads, pipeline, and campaign performance.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.GOOGLE_SHEETS,
    name: 'Google Sheets',
    category: 'ANALYTICS',
    altCategories: ['PPC'],
    authType: 'OAUTH',
    authLabel: 'Google OAuth',
    description: 'Import custom data from Google Sheets into dashboards and reports as a flexible data source.',
    isImplemented: true,
  },

  // ─── Call Tracking ────────────────────────────────────────────────────────
  {
    key: IntegrationPlatform.CALLRAIL,
    name: 'CallRail',
    category: 'CALL_TRACKING',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Track inbound calls, call sources, duration, and lead quality from CallRail.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.CALLTRACKING_METRICS,
    name: 'CallTrackingMetrics',
    category: 'CALL_TRACKING',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull call tracking data — calls, sources, duration, and conversion tracking from CallTrackingMetrics.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.TWILIO,
    name: 'Twilio',
    category: 'CALL_TRACKING',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Sync Twilio call and SMS data — call volume, duration, SMS campaigns, and conversion events.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.WHATCONVERTS,
    name: 'WhatConverts',
    category: 'CALL_TRACKING',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Import call, form, chat, and transaction conversion data from WhatConverts.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.MARCHEX,
    name: 'Marchex',
    category: 'CALL_TRACKING',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull call analytics, conversational intelligence, and attribution data from Marchex.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.AVANSER,
    name: 'Avanser',
    category: 'CALL_TRACKING',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Track call conversions and attribution data from the Avanser call tracking platform.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.CALLSOURCE,
    name: 'CallSource',
    category: 'CALL_TRACKING',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Import call tracking and analytics data from CallSource.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.DELACON,
    name: 'Delacon',
    category: 'CALL_TRACKING',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Sync call tracking and attribution data from the Delacon platform.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.WILDJAR,
    name: 'WildJar',
    category: 'CALL_TRACKING',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull call tracking, transcription, and attribution data from WildJar.',
    isImplemented: true,
  },

  // ─── Local & Reputation ───────────────────────────────────────────────────
  {
    key: IntegrationPlatform.BRIGHTLOCAL,
    name: 'BrightLocal',
    category: 'LOCAL',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Monitor local SEO rankings, citation accuracy, and reputation scores from BrightLocal.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.TRUSTPILOT,
    name: 'Trustpilot',
    category: 'LOCAL',
    authType: 'OAUTH',
    authLabel: 'OAuth',
    description: 'Track Trustpilot review scores, review count, and rating trends over time.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.YELP,
    name: 'Yelp',
    category: 'LOCAL',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Monitor Yelp business ratings, review count, and customer impression metrics.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.BIRDEYE,
    name: 'Birdeye',
    category: 'LOCAL',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull review scores, sentiment, and reputation data across platforms from Birdeye.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.YEXT,
    name: 'Yext',
    category: 'LOCAL',
    authType: 'OAUTH',
    authLabel: 'OAuth',
    description: 'Sync Yext knowledge graph data — listing accuracy, review scores, and local search performance.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.GATHERUP,
    name: 'GatherUp',
    category: 'LOCAL',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Track customer review requests, review scores, and feedback trends from GatherUp.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.GRADE_US,
    name: 'Grade.us',
    category: 'LOCAL',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Monitor review generation and reputation management metrics from Grade.us.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.SYNUP,
    name: 'Synup',
    category: 'LOCAL',
    authType: 'API_KEY',
    authLabel: 'API Key',
    description: 'Pull local listing accuracy, review scores, and presence data from Synup.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.VENDASTA,
    name: 'Vendasta',
    category: 'LOCAL',
    authType: 'OAUTH',
    authLabel: 'OAuth',
    description: 'Sync Vendasta reputation management and local marketing data into your dashboards.',
    isImplemented: true,
  },

  // ─── Database / Warehouse ─────────────────────────────────────────────────
  {
    key: IntegrationPlatform.GOOGLE_BIGQUERY,
    name: 'Google BigQuery',
    category: 'DATABASE',
    authType: 'OAUTH',
    authLabel: 'Google OAuth',
    description: 'Query custom datasets from Google BigQuery and visualise them in dashboards.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.AMAZON_REDSHIFT,
    name: 'Amazon Redshift',
    category: 'DATABASE',
    authType: 'BOTH',
    authLabel: 'API Key',
    description: 'Connect to Amazon Redshift data warehouses and pull custom metrics into dashboards.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.MYSQL_DB,
    name: 'MySQL',
    category: 'DATABASE',
    authType: 'BOTH',
    authLabel: 'Credentials',
    description: 'Connect to a MySQL database and import custom query results as dashboard metrics.',
    isImplemented: true,
  },
  {
    key: IntegrationPlatform.SNOWFLAKE,
    name: 'Snowflake',
    category: 'DATABASE',
    authType: 'BOTH',
    authLabel: 'API Key',
    description: 'Pull data from Snowflake data warehouses and display it in custom dashboards.',
    isImplemented: true,
  },
];

/** Lookup a platform by its enum key. */
export function getPlatformMeta(key: IntegrationPlatform): PlatformMeta | undefined {
  return PLATFORM_CATALOG.find((p) => p.key === key);
}

/** All platforms for a given category (includes altCategories). */
export function getPlatformsByCategory(category: IntegrationCategory): PlatformMeta[] {
  return PLATFORM_CATALOG.filter(
    (p) => p.category === category || p.altCategories?.includes(category),
  );
}

/** All implemented platforms. */
export const IMPLEMENTED_PLATFORMS = new Set<IntegrationPlatform>(
  PLATFORM_CATALOG.filter((p) => p.isImplemented).map((p) => p.key),
);
